# optimization
lr: 0.0003
optimizer: "Adam"
batch_size: 64
loss: "bce"
# data
num_workers: 24
pin_memory: True
# model
model: Unet
backbone: resnet18
pretrained: imagenet
load_from: False
# data augmentation
train_trans:
  Resize:
    width: 224
    height: 224
val_trans:
  Resize:
    width: 224
    height: 224
# training params
gpus: 1
precision: 16
max_epochs: 50
# debugging options
train_batches: 1.
shuffle_train: True
val_batches: 1.
val_with_train: False
log: True
