# optimization
lr: 0.001
optimizer: Adam
batch_size: 5
loss: dice
# data
num_workers: 24
pin_memory: True
# model
model: Unet
backbone: resnet18
pretrained: imagenet
load_from: False
# data augmentation
train_trans:
  Resize:
    width: 256
    height: 256
val_trans:
  Resize:
    width: 256
    height: 256
# training params
gpus: 1
precision: 16
max_epochs: 100
# debugging options
train_batches: 1
shuffle_train: False
val_batches: 1
val_with_train: True
log: False
