# optimization
lr: 0.00001
optimizer: "Adam"
batch_size: 64
loss: "bce"
scheduler:
  OneCycleLR:
    pct_start: 0.05
    max_lr: 0.0003
    total_steps: 100
    verbose: True
# data
num_workers: 24
pin_memory: True
# model
model: DeepLabV3Plus
backbone: se_resnext50_32x4d
pretrained: imagenet
load_from: False
# data augmentation
train_trans:
  PadIfNeeded:
    min_width: 224
    min_height: 224
    border_mode: 0
  RandomResizedCrop:
    width: 224
    height: 224
  HorizontalFlip: {}
  VerticalFlip: {}
  Transpose: {}
  Rotate: {}
  GridDistortion: {}
val_trans:
  Resize:
    width: 224
    height: 224
# training params
gpus: 1
precision: 16
max_epochs: 100
# debugging options
train_batches: 1.
shuffle_train: True
val_batches: 1.
val_with_train: False
log: True
