# optimization
lr: 0.0001
optimizer: "Adam"
batch_size: 1
gradient_clip_val: 1.
# data
num_workers: 0
pin_memory: True
subset: 0.001
# model
img_size: 128
patch_size: 16
embed_dim: 256
nhead: 4
num_encoder_layers: 6
num_decoder_layers: 6
dropout: 0.
max_len: 277
load_from: False
# data augmentation
train_trans:
  Resize:
    width: 128
    height: 128
val_trans:
  Resize:
    width: 128
    height: 128
# training params
gpus: 1
precision: 16
max_epochs: 100
# debugging options
train_batches: 1
shuffle_train: False
val_batches: 1
val_with_train: True
log: False
