backbone: vit_base_patch16_384
batch_size: 32
data: data_extra
es_start_from: 5
gpus: 1
lr: 0.00036
max_epochs: 15
model: ViT
num_workers: 0
optimizer: Adam
patience: 3
pin_memory: true
precision: 16
pretrained: true
scheduler:
  OneCycleLR:
    max_lr: 0.00036
    pct_start: 0.2
    total_steps: 15
    verbose: true
size: 384
subset: 0.0
train_batches: 1.0
train_trans:
  HorizontalFlip: {}
  Normalize: {}
  PadIfNeeded:
    border_mode: 0
    min_height: 384
    min_width: 384
  RandomResizedCrop:
    height: 384
    width: 384
  ShiftScaleRotate: {}
  Transpose: {}
  VerticalFlip: {}
unfreeze: 0
val_batches: 1.0
val_trans:
  CenterCrop:
    height: 384
    width: 384
  Normalize: {}
  PadIfNeeded:
    border_mode: 0
    min_height: 384
    min_width: 384
val_with_train: false
